namespace MbrsUI
{
    runtimeclass ImageView
    {
       ImageView(String path, String fileName);

       String path { get;};

       String fileName { get; };
    }

    runtimeclass TagCheckbox : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
       TagCheckbox (String name, Windows.Foundation.IReference<Boolean> isUsed);

       String name{ get; };

       Windows.Foundation.IReference<Boolean> isUsed{ get;};
    }

    [default_interface]
    runtimeclass Page : Windows.UI.Xaml.Controls.UserControl
    {
       Page();

       void setDesktopCallback(UInt64 ptr);
    }
}
