namespace MbrsUI
{
    runtimeclass ImageView
    {
       ImageView(String path, String fileName);

       String path { get;};

       String fileName { get; };
    }

    runtimeclass TagCheckbox
    {
       TagCheckbox (String name, Boolean isUsed);

       String name { get; };

       Boolean isUsed { get; };
    }

    [default_interface]
    runtimeclass Page : Windows.UI.Xaml.Controls.UserControl
    {
       Page();

       void setDesktopCallback(UInt64 ptr);
    }
}
