namespace MbrsUI
{
    runtimeclass StringWrapper : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
       StringWrapper(String text);

       String text{ get;};
    }

    [default_interface]
    runtimeclass Page : Windows.UI.Xaml.Controls.UserControl
    {
       Page();

       void setDesktopCallback(UInt64 ptr);
    }
}
